# Generated by Django 3.1.1 on 2020-09-17 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_max_security', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=30)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uuid', models.TextField(primary_key=True, serialize=False)),
                ('is_soldier', models.BooleanField(default=False)),
                ('is_major', models.BooleanField(default=False)),
                ('jail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jail')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slave_timer', models.IntegerField()),
                ('jail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jail')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.player')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.town'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Plugin'), (2, 'Guide'), (3, 'Town')])),
                ('related_pages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.page')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
                ('town', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.town')),
            ],
        ),
        migrations.AddField(
            model_name='jail',
            name='location_max',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_max', to='api.location'),
        ),
        migrations.AddField(
            model_name='jail',
            name='location_min',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_min', to='api.location'),
        ),
        migrations.AddField(
            model_name='jail',
            name='slave_spawn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slave_spawn', to='api.location'),
        ),
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.TextField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
    ]
