# Generated by Django 3.1.1 on 2020-09-27 04:42

import CD.api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_max_security', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('x', models.DecimalField(decimal_places=15, max_digits=23, validators=[CD.api.models.max_world_size])),
                ('y', models.DecimalField(decimal_places=15, max_digits=18, validators=[CD.api.models.max_world_height])),
                ('z', models.DecimalField(decimal_places=15, max_digits=23, validators=[CD.api.models.max_world_size])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_soldier', models.BooleanField(default=False)),
                ('is_mayor', models.BooleanField(default=False)),
                ('jail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jail')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax', models.FloatField()),
                ('isSellable', models.BooleanField()),
                ('canBuild', models.BooleanField()),
                ('canDestroy', models.BooleanField()),
                ('location_max', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_location_max', to='api.location')),
                ('location_min', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_location_min', to='api.location')),
                ('player', models.ManyToManyField(blank=True, to='api.Player')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.town')),
            ],
        ),
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisoner_timer', models.IntegerField()),
                ('jail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jail')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.player')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.town'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', tinymce.models.HTMLField()),
                ('type', models.IntegerField(choices=[(1, 'Plugin'), (2, 'Guide'), (3, 'Town')])),
                ('related_pages', models.ManyToManyField(blank=True, related_name='_page_related_pages_+', to='api.Page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
                ('town', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.town')),
            ],
        ),
        migrations.AddField(
            model_name='jail',
            name='location_max',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jail_location_max', to='api.location'),
        ),
        migrations.AddField(
            model_name='jail',
            name='location_min',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jail_location_min', to='api.location'),
        ),
        migrations.AddField(
            model_name='jail',
            name='prisoner_spawn',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prisoner_spawn', to='api.location'),
        ),
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('usage', models.CharField(max_length=255)),
                ('permission', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.page')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.command')),
            ],
        ),
    ]
